# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(800, 550)
        login.setMinimumSize(QtCore.QSize(800, 550))
        login.setMaximumSize(QtCore.QSize(1200, 650))
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(6, 2, 791, 541))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap("utils/images/Untitled.jpg"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 20, 161, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("utils/images/Pictogrammers-Material-Bank-circle.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color:rgb(179, 0, 0)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 200, 401, 301))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0,90);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.usernamefield = QtWidgets.QLineEdit(self.centralwidget)
        self.usernamefield.setGeometry(QtCore.QRect(270, 260, 281, 41))
        self.usernamefield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.usernamefield.setObjectName("usernamefield")
        self.passwordfield = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordfield.setGeometry(QtCore.QRect(270, 360, 281, 41))
        self.passwordfield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordfield.setObjectName("passwordfield")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 220, 91, 31))
        self.label_4.setStyleSheet("font: 14pt \"Cambria\";\n"
"color: rgb(221, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 320, 91, 31))
        self.label_5.setStyleSheet("font: 14pt \"Cambria\";\n"
"color: rgb(221, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.loginbutt = QtWidgets.QPushButton(self.centralwidget)
        self.loginbutt.setGeometry(QtCore.QRect(270, 432, 81, 31))
        self.loginbutt.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.loginbutt.setObjectName("loginbutt")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(270, 410, 281, 16))
        self.error.setStyleSheet("font: 10pt \"Cambria\";\n"
"color: rgb(221, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "bank system"))
        self.label_2.setText(_translate("login", "bank system"))
        self.label_4.setText(_translate("login", "username"))
        self.label_5.setText(_translate("login", "password"))
        self.loginbutt.setText(_translate("login", "log in"))
import res1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
