# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(945, 664)
        Welcome.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(Welcome)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 951, 661))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap("utils/images/Untitled.jpg"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.MoneyTransfer = QtWidgets.QPushButton(self.centralwidget)
        self.MoneyTransfer.setGeometry(QtCore.QRect(810, 20, 101, 31))
        self.MoneyTransfer.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.MoneyTransfer.setObjectName("MoneyTransfer")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 300, 931, 321))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0, 100);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 300, 61, 41))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(730, 320, 91, 31))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 320, 91, 31))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 430, 91, 31))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 500, 91, 31))
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 350, 91, 31))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 351, 251))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0, 100);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 351, 221))
        self.tableWidget.setStyleSheet("background-color: rgb(192, 190, 255);\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.dcn = QtWidgets.QLineEdit(self.centralwidget)
        self.dcn.setGeometry(QtCore.QRect(536, 20, 119, 31))
        self.dcn.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.dcn.setText("")
        self.dcn.setAlignment(QtCore.Qt.AlignCenter)
        self.dcn.setObjectName("dcn")
        self.balance = QtWidgets.QLineEdit(self.centralwidget)
        self.balance.setGeometry(QtCore.QRect(660, 20, 120, 31))
        self.balance.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.balance.setText("")
        self.balance.setAlignment(QtCore.Qt.AlignCenter)
        self.balance.setObjectName("balance")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 60, 531, 211))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0, 100);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(580, 60, 351, 211))
        self.tableWidget_2.setStyleSheet("background-color: rgb(192, 190, 255);\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.DTransaction = QtWidgets.QPushButton(self.centralwidget)
        self.DTransaction.setGeometry(QtCore.QRect(420, 148, 101, 31))
        self.DTransaction.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.DTransaction.setObjectName("DTransaction")
        self.NTransaction = QtWidgets.QPushButton(self.centralwidget)
        self.NTransaction.setGeometry(QtCore.QRect(420, 70, 101, 31))
        self.NTransaction.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.NTransaction.setObjectName("NTransaction")
        self.nEditLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nEditLine.setGeometry(QtCore.QRect(425, 108, 91, 20))
        self.nEditLine.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.nEditLine.setAlignment(QtCore.Qt.AlignCenter)
        self.nEditLine.setObjectName("nEditLine")
        self.dateEditLine = QtWidgets.QLineEdit(self.centralwidget)
        self.dateEditLine.setGeometry(QtCore.QRect(415, 181, 161, 21))
        self.dateEditLine.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.dateEditLine.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditLine.setObjectName("dateEditLine")
        self.dateEditLine_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.dateEditLine_2.setGeometry(QtCore.QRect(415, 203, 161, 21))
        self.dateEditLine_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.dateEditLine_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditLine_2.setObjectName("dateEditLine_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(640, 360, 291, 231))
        self.tableWidget_3.setAutoFillBackground(False)
        self.tableWidget_3.setStyleSheet("background-color: rgb(192, 190, 255);")
        self.tableWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.tableWidget_3.horizontalHeader().setVisible(True)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget_3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_4.setGeometry(QtCore.QRect(330, 360, 291, 231))
        self.tableWidget_4.setStyleSheet("background-color: rgb(192, 190, 255);")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(7)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(70)
        self.loanID = QtWidgets.QLineEdit(self.centralwidget)
        self.loanID.setGeometry(QtCore.QRect(470, 320, 119, 31))
        self.loanID.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.loanID.setText("")
        self.loanID.setAlignment(QtCore.Qt.AlignCenter)
        self.loanID.setObjectName("loanID")
        self.loanID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.loanID_2.setGeometry(QtCore.QRect(130, 350, 119, 31))
        self.loanID_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.loanID_2.setText("")
        self.loanID_2.setAlignment(QtCore.Qt.AlignCenter)
        self.loanID_2.setObjectName("loanID_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 570, 281, 51))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.label_5.setText("")
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.MoneyTransfer_4 = QtWidgets.QPushButton(self.centralwidget)
        self.MoneyTransfer_4.setGeometry(QtCore.QRect(150, 465, 91, 31))
        self.MoneyTransfer_4.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.MoneyTransfer_4.setObjectName("MoneyTransfer_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 430, 101, 21))
        self.comboBox.setStyleSheet("background-color: rgb(170, 0, 0, 250);\n"
"color : rgb(255, 255, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.cscn = QtWidgets.QComboBox(self.centralwidget)
        self.cscn.setGeometry(QtCore.QRect(410, 20, 121, 31))
        self.cscn.setStyleSheet("color : rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 170, 255, 100);")
        self.cscn.setObjectName("cscn")
        self.cAcc_num = QtWidgets.QComboBox(self.centralwidget)
        self.cAcc_num.setGeometry(QtCore.QRect(430, 230, 121, 31))
        self.cAcc_num.setStyleSheet("color : rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 170, 255, 100);")
        self.cAcc_num.setObjectName("cAcc_num")
        self.cAcc_num_2 = QtWidgets.QComboBox(self.centralwidget)
        self.cAcc_num_2.setGeometry(QtCore.QRect(20, 465, 121, 31))
        self.cAcc_num_2.setStyleSheet("color : rgb(255, 255, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 170, 255, 100);")
        self.cAcc_num_2.setObjectName("cAcc_num_2")
        Welcome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Welcome)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 21))
        self.menubar.setObjectName("menubar")
        Welcome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Welcome)
        self.statusbar.setObjectName("statusbar")
        Welcome.setStatusBar(self.statusbar)

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "MainWindow"))
        self.MoneyTransfer.setText(_translate("Welcome", "money transfer"))
        self.label_2.setText(_translate("Welcome", "loan:"))
        self.pushButton.setText(_translate("Welcome", "my loans"))
        self.pushButton_2.setText(_translate("Welcome", "installment list"))
        self.pushButton_3.setText(_translate("Welcome", "loan application"))
        self.pushButton_4.setText(_translate("Welcome", "loan amount"))
        self.pushButton_5.setText(_translate("Welcome", "payment"))
        self.label_3.setText(_translate("Welcome", " my accounts:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Welcome", "acc num"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Welcome", "username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Welcome", "active loan"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Welcome", "balance"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Welcome", "blocked"))
        self.dcn.setPlaceholderText(_translate("Welcome", "destination card number"))
        self.balance.setPlaceholderText(_translate("Welcome", "balance"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Welcome", "source card num"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Welcome", "destination card num"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Welcome", "year"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Welcome", "month"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Welcome", "day"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Welcome", "hour"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Welcome", "min"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Welcome", "amount"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Welcome", "successfull"))
        self.DTransaction.setText(_translate("Welcome", "D transaction"))
        self.NTransaction.setText(_translate("Welcome", "N transaction"))
        self.nEditLine.setPlaceholderText(_translate("Welcome", "input the number"))
        self.dateEditLine.setPlaceholderText(_translate("Welcome", "start date (format 2023-01-01)"))
        self.dateEditLine_2.setPlaceholderText(_translate("Welcome", "start date (format 2023-01-01)"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Welcome", "loan ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Welcome", "acc number"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Welcome", "amount"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Welcome", "payments"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Welcome", "username"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Welcome", "loan ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Welcome", "pay num"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Welcome", "year"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Welcome", "month"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Welcome", "day"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("Welcome", "amount"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("Welcome", "paid"))
        self.loanID.setPlaceholderText(_translate("Welcome", "loan_ID"))
        self.loanID_2.setPlaceholderText(_translate("Welcome", "loan_ID"))
        self.MoneyTransfer_4.setText(_translate("Welcome", "Block account"))
        self.comboBox.setItemText(0, _translate("Welcome", "normal type"))
        self.comboBox.setItemText(1, _translate("Welcome", "loan to by housing"))
        self.comboBox.setItemText(2, _translate("Welcome", "loan to by a laptop"))
        self.cscn.setPlaceholderText(_translate("Welcome", "source card number"))
        self.cAcc_num.setPlaceholderText(_translate("Welcome", "account number"))
        self.cAcc_num_2.setPlaceholderText(_translate("Welcome", "account number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Welcome = QtWidgets.QMainWindow()
    ui = Ui_Welcome()
    ui.setupUi(Welcome)
    Welcome.show()
    sys.exit(app.exec_())
