# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\1 DRIVE C\old pc\sara\Daneshgah\5\db\پروژه\project_ui\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_panel(object):
    def setupUi(self, admin_panel):
        admin_panel.setObjectName("admin_panel")
        admin_panel.resize(795, 597)
        self.centralwidget = QtWidgets.QWidget(admin_panel)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap("f:\\1 DRIVE C\\old pc\\sara\\Daneshgah\\5\\db\\پروژه\\project_ui\\utils/images/Untitled.jpg"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.usr1 = QtWidgets.QLineEdit(self.centralwidget)
        self.usr1.setGeometry(QtCore.QRect(31, 30, 120, 31))
        self.usr1.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.usr1.setText("")
        self.usr1.setAlignment(QtCore.Qt.AlignCenter)
        self.usr1.setObjectName("usr1")
        self.pass1 = QtWidgets.QLineEdit(self.centralwidget)
        self.pass1.setGeometry(QtCore.QRect(156, 30, 119, 31))
        self.pass1.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.pass1.setText("")
        self.pass1.setAlignment(QtCore.Qt.AlignCenter)
        self.pass1.setObjectName("pass1")
        self.fn = QtWidgets.QLineEdit(self.centralwidget)
        self.fn.setGeometry(QtCore.QRect(280, 30, 120, 31))
        self.fn.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.fn.setText("")
        self.fn.setAlignment(QtCore.Qt.AlignCenter)
        self.fn.setObjectName("fn")
        self.ln = QtWidgets.QLineEdit(self.centralwidget)
        self.ln.setGeometry(QtCore.QRect(405, 30, 119, 31))
        self.ln.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.ln.setText("")
        self.ln.setAlignment(QtCore.Qt.AlignCenter)
        self.ln.setObjectName("ln")
        self.ph = QtWidgets.QLineEdit(self.centralwidget)
        self.ph.setGeometry(QtCore.QRect(529, 30, 120, 31))
        self.ph.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.ph.setText("")
        self.ph.setAlignment(QtCore.Qt.AlignCenter)
        self.ph.setObjectName("ph")
        self.AddCustomer = QtWidgets.QPushButton(self.centralwidget)
        self.AddCustomer.setGeometry(QtCore.QRect(654, 29, 121, 31))
        self.AddCustomer.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.AddCustomer.setObjectName("AddCustomer")
        self.AddAccount = QtWidgets.QPushButton(self.centralwidget)
        self.AddAccount.setGeometry(QtCore.QRect(654, 79, 121, 31))
        self.AddAccount.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.AddAccount.setObjectName("AddAccount")
        self.balance = QtWidgets.QLineEdit(self.centralwidget)
        self.balance.setGeometry(QtCore.QRect(280, 80, 120, 31))
        self.balance.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.balance.setText("")
        self.balance.setAlignment(QtCore.Qt.AlignCenter)
        self.balance.setObjectName("balance")
        self.acc_num = QtWidgets.QLineEdit(self.centralwidget)
        self.acc_num.setGeometry(QtCore.QRect(31, 80, 120, 31))
        self.acc_num.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.acc_num.setText("")
        self.acc_num.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_num.setObjectName("acc_num")
        self.usr2 = QtWidgets.QLineEdit(self.centralwidget)
        self.usr2.setGeometry(QtCore.QRect(156, 80, 119, 31))
        self.usr2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.usr2.setText("")
        self.usr2.setAlignment(QtCore.Qt.AlignCenter)
        self.usr2.setObjectName("usr2")
        self.block_acc = QtWidgets.QPushButton(self.centralwidget)
        self.block_acc.setGeometry(QtCore.QRect(654, 130, 121, 31))
        self.block_acc.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.block_acc.setObjectName("block_acc")
        self.acc_num_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.acc_num_2.setGeometry(QtCore.QRect(30, 130, 120, 31))
        self.acc_num_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.acc_num_2.setText("")
        self.acc_num_2.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_num_2.setObjectName("acc_num_2")
        self.usr3_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.usr3_2.setGeometry(QtCore.QRect(31, 180, 120, 31))
        self.usr3_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.usr3_2.setText("")
        self.usr3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.usr3_2.setObjectName("usr3_2")
        self.chng = QtWidgets.QPushButton(self.centralwidget)
        self.chng.setGeometry(QtCore.QRect(654, 179, 121, 31))
        self.chng.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.chng.setObjectName("chng")
        self.oldP = QtWidgets.QLineEdit(self.centralwidget)
        self.oldP.setGeometry(QtCore.QRect(156, 180, 119, 31))
        self.oldP.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.oldP.setText("")
        self.oldP.setAlignment(QtCore.Qt.AlignCenter)
        self.oldP.setObjectName("oldP")
        self.newP = QtWidgets.QLineEdit(self.centralwidget)
        self.newP.setGeometry(QtCore.QRect(280, 180, 120, 31))
        self.newP.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.newP.setText("")
        self.newP.setAlignment(QtCore.Qt.AlignCenter)
        self.newP.setObjectName("newP")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 230, 381, 251))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0,150);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 230, 361, 251))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0,150);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.usr4 = QtWidgets.QLineEdit(self.centralwidget)
        self.usr4.setGeometry(QtCore.QRect(40, 490, 119, 31))
        self.usr4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.usr4.setText("")
        self.usr4.setAlignment(QtCore.Qt.AlignCenter)
        self.usr4.setObjectName("usr4")
        self.loanID = QtWidgets.QLineEdit(self.centralwidget)
        self.loanID.setGeometry(QtCore.QRect(420, 490, 119, 31))
        self.loanID.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.loanID.setText("")
        self.loanID.setAlignment(QtCore.Qt.AlignCenter)
        self.loanID.setObjectName("loanID")
        self.loanbutt = QtWidgets.QPushButton(self.centralwidget)
        self.loanbutt.setGeometry(QtCore.QRect(220, 490, 151, 31))
        self.loanbutt.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.loanbutt.setObjectName("loanbutt")
        self.installmentBut = QtWidgets.QPushButton(self.centralwidget)
        self.installmentBut.setGeometry(QtCore.QRect(600, 490, 151, 31))
        self.installmentBut.setStyleSheet("\n"
"QPushButton{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,200);\n"
"border-style:inset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Cambria\";\n"
"background-color: rgb(255, 0, 0,100);\n"
"}")
        self.installmentBut.setObjectName("installmentBut")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 240, 357, 231))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: rgb(192, 190, 255);")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(420, 240, 341, 231))
        self.tableWidget_2.setStyleSheet("background-color: rgb(192, 190, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(70)
        admin_panel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(admin_panel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        admin_panel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(admin_panel)
        self.statusbar.setObjectName("statusbar")
        admin_panel.setStatusBar(self.statusbar)

        self.retranslateUi(admin_panel)
        QtCore.QMetaObject.connectSlotsByName(admin_panel)

    def retranslateUi(self, admin_panel):
        _translate = QtCore.QCoreApplication.translate
        admin_panel.setWindowTitle(_translate("admin_panel", "MainWindow"))
        self.usr1.setPlaceholderText(_translate("admin_panel", "username"))
        self.pass1.setPlaceholderText(_translate("admin_panel", "password"))
        self.fn.setPlaceholderText(_translate("admin_panel", "first name "))
        self.ln.setPlaceholderText(_translate("admin_panel", "last name "))
        self.ph.setPlaceholderText(_translate("admin_panel", "phone number"))
        self.AddCustomer.setText(_translate("admin_panel", "add customer"))
        self.AddAccount.setText(_translate("admin_panel", "add account"))
        self.balance.setPlaceholderText(_translate("admin_panel", "balance"))
        self.acc_num.setPlaceholderText(_translate("admin_panel", "account number"))
        self.usr2.setPlaceholderText(_translate("admin_panel", "username"))
        self.block_acc.setText(_translate("admin_panel", "block account"))
        self.acc_num_2.setPlaceholderText(_translate("admin_panel", "account number"))
        self.usr3_2.setPlaceholderText(_translate("admin_panel", "username"))
        self.chng.setText(_translate("admin_panel", "change pass"))
        self.oldP.setPlaceholderText(_translate("admin_panel", "old pass"))
        self.newP.setPlaceholderText(_translate("admin_panel", "new pass"))
        self.usr4.setPlaceholderText(_translate("admin_panel", "username"))
        self.loanID.setPlaceholderText(_translate("admin_panel", "loan_ID"))
        self.loanbutt.setText(_translate("admin_panel", "show all loans"))
        self.installmentBut.setText(_translate("admin_panel", "show installments"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("admin_panel", "loan ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("admin_panel", "acc number"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("admin_panel", "amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("admin_panel", "payments"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("admin_panel", "username"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("admin_panel", "loan ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("admin_panel", "pay num"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("admin_panel", "year"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("admin_panel", "month"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("admin_panel", "day"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("admin_panel", "amount"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("admin_panel", "paid"))
